### ISSUE TITLE
[info][chapter 19] prototype-pollution

### ISSUE THREAD

**Issue by paengjiwoo** [240818-deepdive/javascript-deep-dive#16]
Prototype-Pollution(프로토타입 오염 공격)은 자바스크립트의 프로토타입 기반 상속 모델에 의해 발생하며, 공격자가 전역 객체 프로토타입에 임의의 속성과 메서드를 도입하거나 수정할 수 있는 취약점입니다. 

아래 글에서, Prototype-Pollution 공격 사례와 대응 방안에 대해 잘 설명하고 있어 공유합니다.

[Prototype-Pollution 취약점을 이용한 공격사례 분석 및 대응방안](https://www.igloo.co.kr/security-information/prototype-pollution-%EC%B7%A8%EC%95%BD%EC%A0%90%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EA%B3%B5%EA%B2%A9%EC%82%AC%EB%A1%80-%EB%B6%84%EC%84%9D-%EB%B0%8F-%EB%8C%80%EC%9D%91%EB%B0%A9%EC%95%88/)

- 참고: [프로토타입 오염 공격 취약점, 자바스크립트 앱 복잡성 증가로 위협 거세져](https://m.boannews.com/html/detail.html?idx=129710)
---

추가적으로 react에서 활용할 수 있을만한 prototype-pollution을 예방하는 방법도 찾아보았습니다.

1. 객체 병합시에 반복문 대신 스프레드 연산자 또는 깊은 복사 활용
  - 반복문 순회는 객체의 모든 열거 가능한 속성이 대상이고, prototype 체인의 속성도 포함하기 때문입니다. 
  ```js
  const mergeObjects = (target, source) => {
  for (let key in source) {
    if (typeof source[key] === 'object') {
      target[key] = mergeObjects(target[key], source[key]);
    } else {
      target[key] = source[key];
    }
    }
    return target;
  };

  // 공격 예시
  const numberData = { __proto__: { number: 1 } };
  const safeObject = {};
  mergeObjects(safeObject, numberData);
  console.log(safeObject.number); // 1
  console.log({}.number); // 1 (공격자가 __proto__ 속성을 이용해 전역 Object.prototype을 오염)
  ```

  2. 불변성 라이브러리 사용
    - 객체의 안전한 복사와 수정을 보장할 수 있습니다.
    
  3. prop 타입 검증 강화

**Comment by codingjamee** [comment]
제인: 반복문대신 스프레드 연산자를 사용하면 왜 폴루션이 방지가 되는지 궁금하다 
지수 : 프로토타입 체인을 끊어버리는걸까?
