### ISSUE TITLE
[question][chapter40] 이벤트 헨들러 프로퍼티 방식과 addEventListener 방식중 어느것을 사용해야할까요?

### ISSUE THREAD

**Issue by JisuPark-dev** [240818-deepdive/javascript-deep-dive#22]
- 프로퍼티 방식과 addEventListener 방식은 중 무엇을 사용하는지는 컨벤션으로 정하기 나름일까요? 
- 만약 둘 중 하나를 컨벤션으로 사용하고 있다면 이유는 무엇인가요?

**Comment by paengjiwoo** [comment]
두 방식 중 사용할 방식을 정하는 것은 1차적으로는 프로젝트 컨벤션으로 정하기 나름이라고 생각합니다. 속도나 성능 면에서 두 방식은 차이가 거의 없어, 어떤 것을 사용한다고 하여 특별히 유리하지는 않기 때문입니다.

다만, 기능상의 차이는 존재하기 때문에 이를 고려하여 컨벤션으로 설정하는 것이 중요할 것 같습니다.
- 프로퍼티 방식의 장점은 간단하고 직관적인 코드를 구성할 수 있다는데에 있습니다. 매우 간단한 로직의 경우 연결이 편리합니다.
- addEventListener 방식의 경우, 하나의 이벤트에 여러 핸들러를 연결할 수 있다는 장점이 있습니다. 또한, removeEventListener를 활용해 이벤트 리스너를 제거할 수 있습니다. 임의의 이벤트 타입을 지정하여 커스텀 이벤트 객체를 생성한 경우, 이벤트 핸들러 등록이 가능하다는 확장성도 갖추고 있습니다.

개인적으로는, 하나의 이벤트에 여러 핸들러를 연결할 수 있는 addEventListener의 유지 보수성이 더 좋아 사용하기 편리하다고 생각하고 있습니다.

사실 직접 개발에 사용하는 것들은 React, Vue 와 같은 것들이다보니 사실상 어트리뷰트 형태를 많이 사용하게 되는 것 같습니다. 어트리뷰트를 기본으로 하고, 필요에 의해 addEventListener 방식을 추가 사용하게 되는 것 같습니다.
