### ISSUE TITLE
[question][chapter40] 캡처링 캐치해서 뭐할까요?

### ISSUE THREAD

**Issue by JisuPark-dev** [240818-deepdive/javascript-deep-dive#23]
찾아본바로는 캡처링은 거의 사용하지 않는다고 하는데요...!

https://ko.javascript.info/bubbling-and-capturing

여기에 캡처이 관련된 부분이 이해하기 쉽게 클릭 이벤트로 구현을 해놔서 공유드립니다.

저는 개인적으로 캡처링 단계를 사용한다고 하면...

타겟단계에서 특정한 값이 변한다고 가정했을 때, 변하기 전과 변한 후의 값을 둘다 기록해야하는 경우에 캡처링 이벤트를 작동시킬 것 같습니다...

**Comment by paengjiwoo** [comment]
저도 캡처링을 보고 어떤 상황에서 사용해야하는지 조금 의문이 생겼습니다. 저의 경우 한번도 활용해본적이 없습니다..

말씀해주신 상황에서도 사용해볼 수 있을 것 같고, 
claude 선생님께 여쭈어보니 이벤트 로깅에 사용해보라는 추천을 해주셨습니다.
```js
document.addEventListener('click', function(event) {
    logEvent('click', event.target);
}, true);

function logEvent(eventType, element) {
    console.log(`Event: ${eventType}, Target: ${element.tagName}, Time: ${new Date()}`);
    // 여기서 로그를 서버로 전송하거나 로컬 스토리지에 저장할 수 있습니다.
}
```
click 이벤트 타깃을 document로 설정해 앱에서 발생하는 사용자 상호작용이나 시스템 이벤트를 기록할 수 있습니다.

**Comment by JisuPark-dev** [comment]
답변해주신거 보다보니, 궁금해진것이.
프론트앤드에서 사용자 상호작용을 어디까지 기록하고 계신가요? 저희는 GA를 특정 버튼이나 동작에 붙여서 확인하고 있는 걸로 알고 있습니다.
sentry에 에러가 뜨면 알람이 가긴 하지만, 에러가 아닌 인터렉션에 대해서는 기록을 하지 않고 있습니다.
