### ISSUE TITLE
[question][chapter13] 렉시컬 환경에서 스코프 체이닝이 일어나 변수가 검색되는 과정에 대해서 좀 더 자세히 설명해주세요

### ISSUE THREAD

**Issue by souplim** [240818-deepdive/javascript-deep-dive#3]
chapter13
p.195
렉시컬 환경

렉시컬 환경에서 스코프 체이닝이 일어나 변수가 검색되는 과정에 대해서 좀 더 자세히 설명해주세요.

**Comment by JisuPark-dev** [comment]
13장을 읽으면서 저도 같은 질문을 적어놨었는데요! 23장을 읽으면서 어느정도 해소가 되었습니다. 

우선 `렉시컬 환경`에서 스코프 체이닝이 일어나 변수 검색이 되는 과정을 알기 위해서는 렉시컬 환경에 대한 이해가 필요합니다. 

책에 정의된 렉시컬 환경의 정의를 가져오면 '`식별자`와 `식별자에 바인딩된 값`, 그리고 `상위 스코프에 대한 참조`를 기록하는 `자료구조`, 실행 컨텍스트를 구성하는 컴포넌트.'라고 정의되어 있습니다. 

저는 위 말을 '실행 컨텍스트라는 것이 '렉시컬 환경'이라는 것으로 구성되어 있구나! 우리가 Array, List 같은 자료구조에 값을 저장하듯이, 실행컨텍스트는 렉시컬 환경이라는 자료구조에다가 값을 저장한다. 만약 해당 스코프에서 식별자를 찾지 못하면 상위 스코프로 가서 식별자를 찾기 위해서 상위 스코프의 참조 값(주소값)도 같이 가지고 있는 거구나'라고 생각했어요. 

> 저희가 소위 '렉시컬 환경'이라고 부르는 자료구조는 크게 2가지 파트로 구성됩니다. 하나는 `값을 저장하는 부분 - 환경레코드`, 다른 하나는 `상위 스코프에 대한 참조값(주소값)`을 가지고 있는 부분입니다.

**Comment by JisuPark-dev** [comment]
만약 우리가 전역 객체(예: window 객체)를 사용한다고 가정해봅시다.

우선, 자바스크립트 코드가 실행될 때 **전역 실행 컨텍스트(Global Execution Context)**가 생성됩니다. 이 전역 실행 컨텍스트는 **전역 렉시컬 환경(Global Lexical Environment)**을 포함합니다.

전역 렉시컬 환경은 **전역 환경 레코드(Global Environment Record)**와 **외부 렉시컬 환경 참조(Outer Lexical Environment Reference)**로 구성됩니다. 전역 렉시컬 환경의 경우, 외부 렉시컬 환경 참조는 존재하지 않기 때문에 null로 설정됩니다.

전역 환경 레코드는 **객체 환경 레코드(Object Environment Record)**와 **선언적 환경 레코드(Declarative Environment Record)**로 구성됩니다.

**객체 환경 레코드(Object Environment Record)**는 이미 생성된 전역 객체(window 객체)와 바인딩되어 있습니다. 이 환경 레코드는 전역 객체를 Binding Object로 사용하여, var로 선언된 전역 변수와 함수 선언문을 전역 객체의 프로퍼티와 메서드로 등록합니다.

**선언적 환경 레코드(Declarative Environment Record)**는 let, const, class와 같은 선언이 저장되는 곳입니다. 이곳에는 전역 객체와는 별도로 선언된 변수가 저장되며, 전역 객체의 프로퍼티로 노출되지 않습니다.

따라서, var로 선언된 전역 변수와 함수 선언문은 전역 환경 레코드에 의해 전역 객체의 프로퍼티와 메서드로 등록됩니다. 반면, let, const, class 선언은 전역 객체가 아닌 선언적 환경 레코드에 등록되며, 전역 객체의 프로퍼티로 노출되지 않습니다.

**Comment by JisuPark-dev** [comment]
지수)
전역 스코프: 객체 환경 레코드, 선언적 환경 레코드
함수 스코프: 함수환경레코드(변수 환경 레코드, 선언적 환경 레코드, this 바인딩)
블록 스코프: 선언적 환경 레코드

이렇게 이해했는데 맞을까요?

**Comment by JisuPark-dev** [comment]
세연) 운영체제에서 가상메모리 작동 방식과 비슷하다. 가상메모리도 힙과 스택 영역이 있습니다. 하나씩 메모리가 쌓이면서 스코프도 하나씩 쌓인다. 
환경에 따라서 변수가 달라지고, 환경이라는 의미에서 컨텍스트라고 한게 아닐까 싶습니다.

**Comment by JisuPark-dev** [comment]
1. 블록 환경스코프는 변수환경스코프가 없다
2. 선언적과 변수 환경 스코프가 나눠서 저장된다.
