### ISSUE TITLE
[question][chapter13] 렉시컬 스코프: 13.5절의 예제13-09 설명

### ISSUE THREAD

**Issue by syk25** [240818-deepdive/javascript-deep-dive#6]
예제 13-09가 어떻게 실행되는지 설명부탁드립니다.

**Comment by JisuPark-dev** [comment]
스코프는 `동적 스코프`와 `렉시컬 스코프(정적 스코프)`로 구분된다고 합니다.

```
var x = 1;

function foo(){
    var x = 10;
    bar();
}

function bar(){
    console.log(x);
}

foo();
bar();
```
자바스크립트가 따르는 `렉시컬 스코프`의 경우 해당 함수를 `어디서 호출했는지`가 아니라(위 경우에서는 function foo 함수 내부) `어디서 정의했는지`에(전역 스코프)  따라 `상위 스코프`를 결정합니다. 

bar함수 내부에서 console.log(x)를 실행할 때, bar함수 내부의 환경 변수에서 변수 x의 값을 찾을 수 없다면 `스코프 체인`에 따라 상위 스코프로 이동하면서 변수 x의 값을 찾게 됩니다. 
bar 함수의 상위 스코프는 전역 스코프이므로, 전역 스코프에서 x의 값이 있으면 사용하고 그렇지 않다면 오류를 뱉을 것입니다.

**Comment by JisuPark-dev** [comment]
var x = 1;

function foo(){
    x = 10;
    bar();
}

function bar(){
    console.log(x);
}

foo();
bar();
