### ISSUE TITLE
[question][chapter 38] JS 엔진에는 여러 종류가 있다는데 각 엔진간의 차이점이 뭐가 있을까요?

### ISSUE THREAD

**Issue by JisuPark-dev** [240818-deepdive/javascript-deep-dive#7]
JS엔진에 토크나이저, 파서, 바이트코드 생성기, 인터프리터가 있다고 알고 있습니다.
처음에 자바스크립트 코드를 서버로 부터 응답 받아서-> 토큰화 하고 -> 토큰을 파싱해서 AST만들고 -> AST기반으로 중간 코드인 바이트코드로 만들어서 -> 인터프리터가 실행한다. 고 합니다.

JS엔진에는 여러가지가 있다고 책에서 언급하면서 구글 크롬, Node.js의 V8, 파이어폭스의 spiderMonkey, 사파리의 JavaScriptCore 등이 있다고 하는데요. 이들의 차이점이 무엇인지 궁금합니다.

**Comment by souplim** [comment]
![image](https://github.com/user-attachments/assets/c1e3263c-6659-45e6-8b19-b72161eca25b)
javascript 엔진들이 가지는 전반적으로 동일한 pipeline을 가지고 있습니다.
1. 자바스크립트 엔진: 자바스크립트 소스코드 -> 파싱 ->AST(추상적 구문 트리) 생성
2. 인터프리터: AST를 바탕으로 바이트 코드를 생성
3. 최적화 컴파일러(optimizing complier): 바이트코드 + profiling data -> 최적화된 기계어 생성
profiling data: 실행 시간, 호출 횟수, 메모리 사용량, 가비지 컬렉션 정보, 함수 호출의 순서와 깊이 등 js 코드의 성능을 분석하고 최적화하는 데 사용되는 정보
4. 정확하지 않은 결과가 나왔다면 deoptimize: 기계어 -> 바이트코드

자바스크립트 엔진들 사이에는 optimization pipeline에서 차이가 있습니다.
코드를 빨리 만들어서 실행하는 것과 시간을 더 들여 최적화된 코드로 실행하는 것 사이의 trade off 때문입니다.
1. 인터프리터
	최적화되지 않은 바이트코드를 빠르게 생성합니다.
2. 최적화 컴파일러
	시간을 들여 바이트코드보다 더 효율적인 기계어 코드를 생성합니다.



1. V8
구글이 개발한 엔진으로 Google Chrome, Node.js 등에서 사용합니다.
![image](https://github.com/user-attachments/assets/7b67087e-6dc0-42dc-bf2c-5856a9f151e6)
Ignition(V8의 Interpreter)은 모든 javascript 엔진 인터프리터 중에서 가장 빠릅니다. 어떤 코드를 많이 실행한다고(getting hot) 판단하면 TurboFan(V8의 최적화 코드)으로 보내 프로파일링된 데이터를 기반으로 최적화된 기계어 코드를 생성합니다. TurboFan frontend는 profiling data를 통합하고 기계어 체계를 구축하는 TurboFan의 일부입니다. optimizer가 완료되어 실행 가능한 기계어 코드가 생성되면 이 기계어 코드로 계속 실행합니다.

2. SpiderMonkey
최초의 자바스크립트 엔진으로 FireFox에서 사용합니다.
![image](https://github.com/user-attachments/assets/86069901-60bf-484a-a06b-ec83c8b5fa38)
SpiderMonkey에서는 최적화된 컴파일러가 2개입니다. hot 코드는 먼저 Baseline 컴파일러에서 약간 최적화된 코드인 Baseline 코드로 생성됩니다. 그리고 이는 코드로 실행되는 와중 profiling data와 합쳐져 IonMonkey라는 최적화 컴파일러로 보내져 고도로 최적화됩니다. optimizer의 작업이 끝나면 Baseline 코드 대신 IonMonkey를 실행합니다.

3. Chakra
마이크로소프트가 개발한 엔진으로 Edge 브라우저에서 사용합니다.
![image](https://github.com/user-attachments/assets/615252e3-fe0b-44a5-b8f3-fe51eaa8ed30)
메인 스레드에서 인터프리터가 바이트코드를 실행하는 동안 SimpleJIT 컴파일러는 약간 최적화된 SimpleJIT 코드를 생성합니다. 엔진은 바이트코드 대신 이 코드를 실행합니다. FullJIT 컴파일러에서는 이를 profiling data와 함께 고도로 최적화된 코드를 생성합니다. 이 방식은 보통 컴파일러가 frontend를 실행하는데 비해 훨씬 짧은데 비해 특정 최적화에 필요한 정보를 일부 놓칠 수 있습니다. 

4. JavaScriptCore
애플에서 개발한 엔진으로 Safari와 React Native App에서 사용합니다.
![image](https://github.com/user-attachments/assets/4475155b-0f54-48f9-8be9-7c89ebec7283)
모든 최적화 컴파일러는 메인 js 실행과 동시에 일어나기 때문에 copy 단계가 없습니다. LLInt(Low Level Interpreter)라는 인터프리터에서 Baseline 컴파일러, DFG(Data Flow Graph) 컴파일러, FTL(Faster Than Light) 컴파일러를 거쳐 최적화 코드를 생성합니다. 


참고
https://velog.io/@godori/JavaScript-engine-1
https://shlrur.github.io/javascripts/javascript-engine-fundamentals-optimizing-prototypes/

**Comment by JisuPark-dev** [comment]
답글
