### ISSUE TITLE
[info][chapter22] p.345 strict mode 가 this 바인딩에 영향을 준다는 의미

### ISSUE THREAD

**Issue by souplim** [240818-deepdive/javascript-deep-dive#8]
```
function foo() {
	x = 10;
}
foo();

console.log(x); // 10
```
foo 함수 내에서 선언하지 않은 x 변수에 값 10을 할당하면 스코프 체인을 통해 검색합니다. 전역 스코프에도 x 변수가 존재하지 않기 때문에 참조에러를 발생시킬 것 같지만 자바스크립트 엔진은 전역 객체에 x 프로퍼티를 동적 생성하여 콘솔에는 10이라는 값이 찍히게 됩니다.

strict mode는 자바스크립트 언어의 문법을 좀 더 엄격히 적용하여 오류를 발생시킬 가능성이 높거나 자바스크립트 엔진의 최적화 작업에 문제를 일으킬 수 있는 코드에 명시적인 에러를 발생시킵니다.

```
'use strict';

function foo() {
    x = 10; // ReferenceError: x is not defined
}
foo();
```

strict mode에서 함수를 일반 함수로서 호출하면 this에 undefined가 바인딩됩니다. 생성자 함수가 아닌 일반 함수 내부에서는 this를 사용할 필요가 없기 때문입니다.
```
(function () {
	'use strict';

	function foo() {
		console.log(this); // window -> undefined
	}
	foo();
}());
```

<img width="483" alt="image" src="https://github.com/user-attachments/assets/0354560c-856e-4d52-b149-dfcb9ed38b9c">

**Comment by JisuPark-dev** [comment]
strict 모드에서 this 바인딩이 undefied가 되지 않는 경우는 객체 내에서 메서드 실행하는 것 밖에 없는 것 같아요.
```
"use strict";
const obj = {
    value: 42,
    showThis: function() {
        console.log(this);
    }
};
obj.showThis(); // obj 객체를 참조
```
